### PR TITLE
typo in ec.d

### PR DESCRIPTION
**Pull request by denizzzka**

### CODE REVIEW

**Comment by denizzzka** [comment]
please pay attention to this simple one-letter patch

**Comment by denizzzka** [comment]
img

**Comment by s-ludwig** [comment]
^^ Sorry, completely missed this (being able to properly check e-mails only since about two weeks).

I'd merge this here, but the fix also needs to go upstream. Unfortunately it's not possible to disable pull requests on this fork, but it's only meant to provide some additional DUB support (version tags).

The best solution would probably be if you'd open the pull request against the D-Programing-Deimos based repository and I'd merge from there.

**Comment by denizzzka** [comment]
Done! https://github.com/D-Programming-Deimos/openssl/pull/31

**Comment by s-ludwig** [comment]
Thanks! I'll monitor the pull and merge as soon as it's merged upstream (+ create a new version tag).

**Comment by denizzzka** [comment]
Why don't make merge right now? Patches are identical

**Comment by s-ludwig** [comment]
Hmm... since the histories are identical that should indeed work (unless something else changes upstream). I just want to avoid having to rebase the master branch later.

**Comment by denizzzka** [comment]
ok

**Comment by denizzzka** [comment]
upstream patch is merged

**Comment by s-ludwig** [comment]
Merged and tagged (registry update is still in progress).

**Comment by denizzzka** [comment]
thanks!

**Pull request closed without merging**
